import jsPDF from 'jspdf';
import { Expense } from '../types';
import { formatCurrency } from './currency';
import { format } from 'date-fns';

export function generateInvoice(expense: Expense, businessName?: string, address?: string, username?: string) {
  const doc = new jsPDF();
  
  // Invoice header
  const invoiceNumber = `INV-${expense.id || Date.now()}`;
  const invoiceDate = format(new Date(), 'MMMM dd, yyyy');
  const expenseDate = format(new Date(expense.date), 'MMMM dd, yyyy');
  
  // Company/Business Info
  const companyName = businessName || 'BigSix AutoSales LLC';
  const companyAddress = address || '123 Business Street\nCity, State ZIP';
  
  // Set font and add header
  doc.setFontSize(20);
  doc.text('INVOICE', 20, 20);
  
  doc.setFontSize(12);
  doc.text(companyName, 20, 35);
  doc.setFontSize(10);
  
  // Split address by newlines and add each line
  const addressLines = companyAddress.split('\n');
  let addressYPos = 42;
  addressLines.forEach((line) => {
    doc.text(line, 20, addressYPos);
    addressYPos += 6;
  });
  
  // Invoice details (right side)
  doc.setFontSize(10);
  doc.text(`Invoice #: ${invoiceNumber}`, 150, 20);
  doc.text(`Date: ${invoiceDate}`, 150, 27);
  doc.text(`Service Date: ${expenseDate}`, 150, 34);
  
  // Line separator
  doc.setLineWidth(0.5);
  doc.line(20, 50, 190, 50);
  
  // Bill To section
  doc.setFontSize(12);
  doc.text('Bill To:', 20, 60);
  doc.setFontSize(10);
  const clientName = expense.vendor || 'Client';
  doc.text(clientName, 20, 67);
  
  // Items table header
  let yPos = 85;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Description', 20, yPos);
  doc.text('Date', 100, yPos);
  doc.text('Amount', 160, yPos);
  
  // Line under header
  doc.setLineWidth(0.3);
  doc.line(20, yPos + 3, 190, yPos + 3);
  
  // Item details
  yPos += 10;
  doc.setFont('helvetica', 'normal');
  doc.text(expense.description || 'No description', 20, yPos);
  doc.text(expenseDate, 100, yPos);
  doc.text(formatCurrency(expense.amount, expense.currency), 160, yPos);
  
  // Category and project info
  if (expense.category) {
    yPos += 7;
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(`Category: ${expense.category}`, 20, yPos);
    if (expense.project_name) {
      doc.text(`Project: ${expense.project_name}`, 100, yPos);
    }
    doc.setTextColor(0, 0, 0);
  }
  
  // Total section
  yPos += 15;
  doc.setLineWidth(0.3);
  doc.line(140, yPos, 190, yPos);
  yPos += 8;
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Total:', 140, yPos);
  doc.text(formatCurrency(expense.amount, expense.currency), 160, yPos);
  
  // Footer
  yPos = 270;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Thank you for your business!', 20, yPos);
  doc.text(`Generated by: ${username || 'User'}`, 20, yPos + 5);
  
  // Save the PDF
  const fileName = `Invoice-${invoiceNumber}-${expenseDate.replace(/\s+/g, '-')}.pdf`;
  doc.save(fileName);
}

