import { useState, useEffect } from 'react';
import { Expense } from './types';
import { downloadCSV } from './utils/export';
import { api } from './services/api';
import ExpenseForm from './components/ExpenseForm';
import ExpenseList from './components/ExpenseList';
import ExpenseFilters, { FilterOptions } from './components/ExpenseFilters';
import SummaryCard from './components/SummaryCard';
import ProjectSummary from './components/ProjectSummary';
import Login from './components/Login';
import AdminDashboard from './components/AdminDashboard';

function App() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [user, setUser] = useState<any>(null);
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [filters, setFilters] = useState<FilterOptions>({
    category: '',
    dateFrom: '',
    dateTo: '',
    amountMin: '',
    amountMax: '',
    vendor: '',
    description: '',
    expenseType: '',
    projectName: ''
  });
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    // Check if user is already logged in
    const token = localStorage.getItem('auth_token');
    if (token) {
      checkAuth();
      loadExpenses();
    }
  }, []);

  const checkAuth = async () => {
    try {
      const userData = await api.getCurrentUser();
      setUser(userData);
      setIsAuthenticated(true);
    } catch (error) {
      localStorage.removeItem('auth_token');
      setIsAuthenticated(false);
    }
  };

  const loadExpenses = async () => {
    try {
      setLoading(true);
      const data = await api.getExpenses();
      setExpenses(data);
    } catch (error) {
      console.error('Error loading expenses:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleLogin = async (token: string, userData: any) => {
    localStorage.setItem('auth_token', token);
    setUser(userData);
    setIsAuthenticated(true);
    await loadExpenses();
  };

  const handleLogout = () => {
    localStorage.removeItem('auth_token');
    setIsAuthenticated(false);
    setUser(null);
    setExpenses([]);
  };

  const handleAddExpense = async (expense: Expense) => {
    try {
      // Remove id if it exists (should be generated by server)
      const { id, ...expenseWithoutId } = expense;
      const newExpense = await api.createExpense(expenseWithoutId);
      // Ensure the new expense has all required fields
      if (newExpense && newExpense.id) {
        setExpenses([newExpense, ...expenses]);
      } else {
        throw new Error('Invalid response from server');
      }
    } catch (error: any) {
      console.error('Error adding expense:', error);
      alert('Error adding expense: ' + (error.message || 'Unknown error'));
      throw error; // Re-throw so form knows submission failed
    }
  };

  const handleDeleteExpense = async (id: string | number) => {
    if (confirm('Are you sure you want to delete this expense?')) {
      try {
        await api.deleteExpense(Number(id));
        setExpenses(expenses.filter(exp => exp.id !== id));
      } catch (error: any) {
        alert('Error deleting expense: ' + error.message);
      }
    }
  };

  const handleExport = () => {
    // Apply same filters to export
    const expensesToExport = expenses.filter(expense => {
      if (filters.category && expense.category !== filters.category) return false;
      if (filters.dateFrom && expense.date < filters.dateFrom) return false;
      if (filters.dateTo && expense.date > filters.dateTo) return false;
      if (filters.amountMin && expense.amount < parseFloat(filters.amountMin)) return false;
      if (filters.amountMax && expense.amount > parseFloat(filters.amountMax)) return false;
      if (filters.vendor && expense.vendor && !expense.vendor.toLowerCase().includes(filters.vendor.toLowerCase())) return false;
      if (filters.description && !expense.description.toLowerCase().includes(filters.description.toLowerCase())) return false;
      if (filters.expenseType && expense.expense_type !== filters.expenseType) return false;
      if (filters.projectName) {
        if (!expense.project_name) return false;
        if (!expense.project_name.toLowerCase().includes(filters.projectName.toLowerCase())) return false;
      }
      return true;
    });
    downloadCSV(expensesToExport);
  };

  const handleClearFilters = () => {
    setFilters({
      category: '',
      dateFrom: '',
      dateTo: '',
      amountMin: '',
      amountMax: '',
      vendor: '',
      description: '',
      expenseType: '',
      projectName: ''
    });
  };

  const handleClearAll = async () => {
    if (confirm('Are you sure you want to delete all expenses? This cannot be undone.')) {
      try {
        for (const expense of expenses) {
          await api.deleteExpense(Number(expense.id));
        }
        setExpenses([]);
      } catch (error: any) {
        alert('Error clearing expenses: ' + error.message);
      }
    }
  };

  // Show login if not authenticated
  if (!isAuthenticated) {
    return <Login onLogin={handleLogin} />;
  }

  // Show admin dashboard if user is admin
  if (user?.is_admin) {
    return <AdminDashboard user={user} onLogout={handleLogout} />;
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-5xl font-bold text-gray-900 mb-2">
            {user?.business_name || 'BigSix AutoSales LLC'}
          </h1>
          <p className="text-xl text-gray-600">Business Expense Tracker</p>
            <div className="mt-4">
              <span className="text-sm text-gray-600">
                {user?.username}
                {user?.is_admin && (
                  <span className="ml-2 px-2 py-1 bg-purple-100 text-purple-800 text-xs font-semibold rounded-full">
                    Admin
                  </span>
                )}
              </span>
              <button
                onClick={handleLogout}
                className="ml-4 px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white text-sm font-semibold rounded-lg transition duration-200"
              >
                Logout
              </button>
            </div>
        </div>

        {/* Filters */}
        <ExpenseFilters 
          filters={filters} 
          onFiltersChange={setFilters}
          onClear={handleClearFilters}
        />

        {/* Actions Bar */}
        <div className="mb-6 flex flex-wrap gap-3 justify-center items-center">
          <button
            onClick={handleExport}
            className="px-6 py-2 bg-green-600 hover:bg-green-700 text-white font-semibold rounded-lg transition duration-200"
          >
            📥 Export CSV for Accountant
          </button>

          {expenses.length > 0 && (
            <button
              onClick={handleClearAll}
              className="px-6 py-2 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-lg transition duration-200"
            >
              🗑️ Clear All
            </button>
          )}
        </div>

        {/* Main Content */}
        {loading ? (
          <div className="text-center py-12">
            <p className="text-gray-600">Loading expenses...</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Left Column - Form and Summary */}
            <div className="lg:col-span-1 space-y-6">
              <ExpenseForm 
                onSubmit={handleAddExpense} 
                existingProjects={[...new Set(expenses.map(e => e.project_name).filter(Boolean) as string[])]}
              />
              <SummaryCard expenses={expenses} />
              <ProjectSummary expenses={expenses} />
            </div>

            {/* Right Column - Expense List */}
            <div className="lg:col-span-2">
              <ExpenseList 
                expenses={expenses} 
                onDelete={handleDeleteExpense}
                filters={filters}
              />
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="mt-8 text-center text-gray-600 text-sm">
          <p>© {new Date().getFullYear()} BigSix AutoSales LLC. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}

export default App;
